name: SellCustomItems
version: ${version}
main: me.mapacheee.sellcustom.SellCustomItemsPlugin
api-version: '1.21'
description: ${description}
author: Mapacheee
folia-supported: true
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
    MapacheeeLib:
      load: BEFORE
      required: true
commands:
  buycustomitems:
    description: Open the custom items shop
  sellcustomitems:
    description: Sell custom items admin command
  sc:
    description: Short alias for sellcustomitems
permissions:
  sellcustom.admin:
    description: Admin permission for sellcustomitems
    default: op